In [ ]:
#create any 3 dimensional array and practice indexing

In [ ]:
import numpy as np
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

In [ ]:
element = array_3d[0, 1, 2]
print("Element at [0, 1, 2]:", element)

Element at [0, 1, 2]: 7


In [ ]:
row = array_3d[0, 0, :]
print("First row of first layer:", row)

First row of first layer: [1 2 3 4]


In [ ]:
column = array_3d[:, :, 1]
print("Second column of all layers:", column)

Second column of all layers: [[ 2  6 10]
 [14 18 22]]


In [ ]:
sub_array = array_3d[0, 1:3, 0:2]
print("Sub-array:", sub_array)

Sub-array: [[ 5  6]
 [ 9 10]]


In [ ]:
#create array of suqares of keys of below dictionary
#d = {1:2,2:3,3:4,4:5}

In [ ]:
d = {1: 2, 2: 3, 3: 4, 4: 5}
keys = d.keys()
squares_array = np.array([key**2 for key in keys])
print(squares_array)

[ 1  4  9 16]


In [ ]:
# multiply any 2 dim array to identity matrix (2*2) and comment on result


In [ ]:
import numpy as np
array_2d = np.array([[1, 2],
                     [3, 4]])
identity_matrix = np.identity(2)
result = np.dot(array_2d, identity_matrix)
print("Original array:")
print(array_2d)

print("\nIdentity matrix:")
print(identity_matrix)

print("\nResult:")
print(result)


Original array:
[[1 2]
 [3 4]]

Identity matrix:
[[1. 0.]
 [0. 1.]]

Result:
[[1. 2.]
 [3. 4.]]
